#! /bin/bash -e
#
# print 5 random formulae
#
# Usage:
#   brew random [<n>]
#
# <n>: default is 5.
#
# Dependencies:
#   brew install coreutils

__brew_random() {
  local n=${1:-5}

  cd $HOMEBREW_PREFIX
  \ls -1g Library/Formula/*.rb \
    | grep -v -- '->' \
    | cut -d/ -f3 \
    | sed 's/\.rb$//' \
    | gshuf \
    | head -$n \
    | xargs brew desc
}

__brew_random $*
