#! /bin/bash -e

# brew fixup: You executed `brew done`, then made some changes again, then...
#             `brew fixup` is here for you.
#
# Usage:
#     brew fixup <formula> <change>
#   change: a short identifier for the change, e.g. "test", "modernize"
__brew_fixup() {
  local formula=$1
  local change=$2
  local branch="${formula}-${change}"
  local fork=`git config github.user`/homebrew
  local open_cmd=
  local tmp=

  brew audit --strict $formula

  cd $HOMEBREW_PREFIX

  git checkout $branch
  git add Library/Formula/${formula}.rb
  git commit --amend --no-edit
  git push -f "git@github.com:$fork"
  git checkout master

  sleep 0.2 # wait for GitHub to process the new stuff
  open "https://github.com/$fork/compare/${branch}?expand=1"
}
__brew_fixup $*
