#! /bin/bash -e
# print 5 random formulae
# dependencies:
#   brew install coreutils
cd $HOMEBREW_PREFIX
\ls -1g Library/Formula/*.rb \
  | grep -v -- '->' \
  | cut -d/ -f3 \
  | sed 's/\.rb$//' \
  | gshuf \
  | head -5 \
  | xargs brew desc
