#! /bin/bash -e

# brew done: for when you’ve done with your changes on a formula and are ready
#            to submit a patch. This only create a branch on your remote repo,
#            you then have to open a PR.
#
# Usage:
#     brew done <formula> <change>
#   change: a short identifier for the change, e.g. "test", "modernize"
#
# Issues:
#   this doesn’t work if you already have a branch for this change.
__brew_done() {
  local formula=$1
  local change=$2
  local branch="${formula}-${change}"
  local fork=`git config github.user`/homebrew-core
  local open_cmd=
  local tmp=/tmp/brew_done.tmp$RANDOM

  [ -z "$BREW_DONE_SKIP_AUDIT" ] && brew audit --strict --online $formula

  cd $(brew --repo)/Library/Taps/homebrew/homebrew-core
  git checkout -b "${formula}-${change}" master
  git add Formula/${formula}.rb
  echo "$formula: $change" >| $tmp
  git commit -t "$tmp"
  rm -f $tmp
  git push -u "git@github.com:$fork" "$branch"
  git checkout master

  sleep 0.2 # wait for GitHub to process the new stuff
  open "https://github.com/$fork/compare/${branch}?expand=1"
}
__brew_done $*
