#! /bin/bash -e
__brew_autobump() {
  local formula=$1
  local url=$2
  local sha256=

  if [ -z $url ] || [ -z $formula ]; then
    echo "Usage: brew autobump <formula> <url>"
    exit 1
  fi

  shift
  shift

  sha256=$(curl -sL "$url" |shasum -a 256|awk '{print $1}')

  brew bump-formula-pr $formula "--url=$url" "--sha256=$sha256" --audit $*
}

__brew_autobump $*
